#!/bin/bash

tmux has-session -t bgo

if [ $? != 0 ]; then
  tmux new-session -s bgo -n editor -d
  
  tmux send-keys -t bgo 'cd $GOPATH/src/github.com/nicholasjackson/building-microservices-in-go' C-m
  tmux send-keys -t bgo 'nvim .' C-m
  
  tmux new-window -n console -t bgo
  tmux send-keys -t bgo:1 'cd $GOPATH/src/github.com/nicholasjackson/building-microservices-in-go' C-m
  tmux split-window -h -t bgo

  tmux select-window -t bgo:0
fi

tmux attach -t bgo
