[General]
  snippetfile = "/Users/nicj/.config/pet/snippet.toml"
  editor = "nvim"
  column = 40
  selectcmd = "fzf-tmux -d 30% --ansi --height=30%"

[Gist]
  file_name = "pet-snippet.toml"
  access_token = ""
  gist_id = ""
  public = false
