[[snippets]]
  description = "Run Nomad in the background"
  command = "nohup nomad agent --config=$HOME/nomad_acl.hcl >~/logs/nomad.log 2>&1 &"
  tag = ["Nomad", "Enterprise"]
  output = ""

[[snippets]]
  description = "Run Consul in the background"
  command = "nohup consul agent -dev >~/logs/consul.log 2>&1 &"
  tag = ["Consul"]
  output = ""

[[snippets]]
  description = "Add Nomad ACL policy"
  command = "curl --request POST --data @nomad_acl.json -H \"X-Nomad-Token: $BOOTSTRAP_TOKEN\" http://localhost:4646/v1/acl/policy/default"
  output = ""

[[snippets]]
  description = "Create Nomad ACL token"
  command = "curl --request POST --data @nomad_token.json -H \"X-Nomad-Token: $BOOTSTRAP_TOKEN\" http://localhost:4646/v1/acl/token"
  output = ""

[[snippets]]
  description = "List Sentinel policy"
  command = "NOMAD_TOKEN=$BOOTSTRAP_TOKEN nomad sentinel list"

[[snippets]]
  description = "Update Sentinel Soft Mandatory policy"
  command = "NOMAD_TOKEN=$BOOTSTRAP_TOKEN nomad sentinel apply -level=soft-mandatory -description=\"restrict size of deployed jobs\" jobs nomad_jobs.sentinel"

[[snippets]]
  description = "Update Sentinel Hard Mandatory policy"
  command = "NOMAD_TOKEN=$BOOTSTRAP_TOKEN nomad sentinel apply -level=hard-mandatory -description=\"hard maximum for job size\" jobs-max nomad_jobs_max_size.sentinel"

[[snippets]]
  description = "Run Nomad job with override"
  command = "NOMAD_TOKEN=$BOOTSTRAP_TOKEN nomad run -policy-override http-echo.nomad"
