[[snippets]]
  description = "Delete evicted pods"
  command = "kubectl get po --all-namespaces --field-selector 'status.phase==Failed' -o json | kubectl delete -f - "
  tag = ["kubernetes"]
  output = ""

[[snippets]]
  description = "Git tag and push"
  command = "git tag <tag> && git push origin <tag>"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "Git delete tag and remote"
  command = "git tag -d <tag> && git push -d origin <tag>"
  tag = ["git"]
  output = ""

[[snippets]]
  description = "FFMPEG generate pallete"
  command = "ffmpeg -y -i <filename> -vf palettegen palette.png"
  output = ""

[[snippets]]
  description = "FFMPEG create animated gif"
  command = "ffmpeg -y -i <filename> -i palette.png -filter_complex paletteuse -r <frames_per_s> <output>"
  output = ""

[[snippets]]
  description = "Create Secret for Ambassador Origin Certs"
  command = "$ kubectl create secret tls ambassador-certs --cert=origin.crt --key=./origin.key"
  output = ""

[[snippets]]
  description = "Scan ip range for connected devices"
  command = "nmap -sn <range>/24"
  output = ""
