[[snippets]]
  description = "Edit Vimfile"
  command = "nvim ~/.vimrc"
  output = ""

[[snippets]]
  description = "Select Swift 4.x"
  command = "sudo xcode-select -s /Applications/Xcode.app"
  output = ""

[[snippets]]
  description = "Select Swift 3.1"
  command = "sudo xcode-select -s /Applications/Xcode-old.app"
  output = ""

[[snippets]]
  description = "Start GPG"
  command = "gpg-agent --daemon --write-env-file ~/.gpg-agent-info"
  output = ""

[[snippets]]
  description = "Terraform debug apply"
  command = "TF_LOG=DEBUG TF_LOG_PATH=./terraform.log terraform apply"
  tag = ["Terraform"]
  output = ""

[[snippets]]
  description = "Create Terraform login for Azure"
  command = "az ad sp create-for-rbac --role=\"Contributor\" --scopes=\"/subscriptions/c0a607b2-6372-4ef3-abdb-dbe52a7b56ba\""
  tag = ["Terraform", "Azure"]
  output = ""

[[snippets]]
  description = "Get Kubernetes config for Azure"
  command = "az acs kubernetes get-credentials --resource-group=$(terraform output resource_group_name) --name=$(terraform output k8s_master_name) --ssh-key-file=/Users/nicj/.ssh/server_rsa"
  tag = ["Terraform", "Azure", "K8s"]
  output = ""

[[snippets]]
  description = "Open Kubernetes Interface Azure"
  command = "az acs kubernetes browse -g $(terraform output resource_group_name) -n $(terraform output k8s_master_name) --ssh-key-file=/Users/nicj/.ssh/server_rsa"
  tag = ["Terraform", "Azure", "K8s"]
  output = ""

[[snippets]]
  description = "Run Nomad in the background"
  command = "nohup nomad agent -dev >~/logs/nomad.log 2>&1 &"
  tag = ["Nomad"]
  output = ""

[[snippets]]
  description = "Run Nomad Enterprise in the background"
  command = "nohup nomad agent --config=$HOME/nomad_acl.hcl >~/logs/nomad.log 2>&1 &"
  tag = ["Nomad", "Enterprise"]
  output = ""

[[snippets]]
  description = "Run Nomad Dev"
  command = "go run main.go commands.go agent --config=$HOME/nomad_acl.hcl"
  tag = ["Nomad"]
  output = ""

[[snippets]]
  description = "Run Consul in the background"
  command = "nohup consul agent -dev >~/logs/consul.log 2>&1 &"
  tag = ["Consul"]
  output = ""

[[snippets]]
  description = "Edit ZSH config"
  command = "nvim ~/.config/nvim/init.vim"
  output = ""

[[snippets]]
  description = "Deploy OpenFaaS info function"
  command = "faas-cli deploy --gateway=$FAAS_GATEWAY --image=functions/nodeinfo:latest --name=info --handler=node main.js"
  output = ""

[[snippets]]
  description = "Invoke OpenFaaS function"
  command = "faas-cli invoke --gateway=$FAAS_GATEWAY -name info"
  output = ""

[[snippets]]
  description = "List OpenFaaS functions"
  command = "faas-cli list --gateway=$FAAS_GATEWAY"
  output = ""

[[snippets]]
  description = "Remove host from known hosts"
  command = "ssh-keygen -R <hostname>"
  output = ""
